lib/internal/process/stdio.js
This is so logging still goes to the console on Windows when `ELECTRON_RUN_AS_NODE` is set and `ELECTRON_NO_ATTACH_CONSOLE` is not set.
Refs https://github.com/electron/electron/issues/5715
Refs https://github.com/electron/electron/pull/7578
=> Call process.log from fallback stream on Windows

src/node_platform.cc, src/node_platform.h
This fixes node_platform so that the upgrade-to-chromium-63 branch can actually get to some of the brightray stuff 👍
=> Fix node_platform for new v8

src/node_platform.cc, src/node_platform.h
Reverts electron/node#28
This change is not needed in the Node.js 8.9.3 branch, which is used for the Chromium **61**.
For Chromium **63** [`temporary-branch-for-chromium-63-upgrade`](https://github.com/electron/node/commits/temporary-branch-for-chromium-63-upgrade) is used (with Node.js 9.2.1).
cc @MarshallOfSound, @zcbenz
=> Revert "Fix node_platform for new v8"

deps/uv/src/win/fs.c
```
win, fs: support unusual reparse points
Allow for running uv_fs_stat and uv_fs_lstat on all reparse points. One
of such points is new OneDrive drive with "files on demand" feature
enabled.
```
put https://github.com/electron/electron/pull/10377 to electeron-1-8-x
will fix https://github.com/electron/electron/issues/11570
=> Backport libuv/libuv#1419

configure, node.gyp, tools/js2c.py
GN doesn't like generated files being mixed in with source code, so this adds options to ./configure to allow the generated config.gypi file to be put elsewhere.
=> Tweaks to ./configure to integrate with GN

src/node_crypto.cc
Small fix to get node building against BoringSSL. Once we upgrade boringssl past https://github.com/google/boringssl/commit/a02ed04d527e1b57b4efaa0b4f9bdbc1ed5975b2 (i.e. in chrome 66), this workaround will no longer be necessary.
=> Workaround for boringssl/openssl incompatibility

tools/js2c.py
blink can not recognize external strings from Node, and it will crash when encountered one, for example executing `window.string_decoder`.
This will fix the first crash described in https://github.com/electron/electron/issues/12835#issuecomment-398941227.
=> Do not use external string as keys

configure
The `-L<path>` syntax isn't recognized by link.exe, and gyp doesn't
translate it properly. Without this, link.exe generates the following
warning and fails to link:
```
LINK : warning LNK4044: unrecognized option '/LC:/Users/nornagon/...'; ignored
```
See nodejs/node#21530
=> chore: make --shared-[...]-path work on Windows

src/node_crypto.cc
By default, OpenSSL will automatically build a certificate chain for a certificate based on trusted certs that are in the X509_STORE. BoringSSL disables this by default (see [#27](https://bugs.chromium.org/p/boringssl/issues/detail?id=27) and [#42](https://bugs.chromium.org/p/boringssl/issues/detail?id=42) on the BoringSSL bug tracker), but nodejs users will expect this behaviour (and indeed, one Electron test depends on it).
=> fix: enable auto cert chaining to match OpenSSL behaviour

BUILD.gn, deps/cares/BUILD.gn, deps/http_parser/BUILD.gn, deps/nghttp2/BUILD.gn, deps/uv/BUILD.gn, src/core.h, src/inspector/BUILD.gn, src/inspector/node_protocol_config.json, src/node_errors.h, tools/generate_config_gypi.py
See electron/maintainers#217.
I think this might actually be similar or easier in terms of maintenance workload when compared to the approach of wrapping node's GYP build.
The list of JS files in lib/ can be deduplicated using gypi_to_gn.
=> gn build files

BUILD.gn, deps/nghttp2/BUILD.gn, deps/uv/BUILD.gn
This reverts commit 6e78f5b02a3f7384f06d1cf44a3a9198d7d7f024.
See electron/libchromiumcontent#682.
=> revert: "fix: [win/x86] don't redefine ssize_t (#57)"

src/node_platform.cc
This reverts commit 19d1193b83c65dff31f11fb4f825c1f64987c24f.
It is safe to merge it now, but the Node reference should be updated only after https://github.com/electron/electron/pull/14503 is backported to `3-0-x`.
=> revert: "FIXME: Comment out TRACE_EVENT_METADATA1 call"

common.gypi
When building native modules using 'npm install' with the system npm,
node-gyp uses the `process.config` of the system npm to fill config.gypi.
If the system npm is not as recent as Electron's node headers, which is
likely, these variables will be missing from that config.gypi, and as a
result, node-gyp will fail when building the native module with an error
like:
gyp: name 'enable_lto' is not defined while evaluating condition
'enable_lto=="true"' in binding.gyp while trying to load binding.gyp
We set default values here to avoid that error message, even though these
aren't technically accurate, because most native modules don't depend on
these values being accurate.
=> fix: make common.gypi backwards-compatible with earlier nodes

src/node_options.h
Fixes a build error on windows.
=> fix: extern template classes shouldn't be dllexported

src/node.cc
=> fix: microsoft-goto warning w/ clang-cl

BUILD.gn, src/node.h, src/node_options.cc, src/node_options.h
On Windows, putting `__dllexport` on a template instantiation declaration causes a compile error, but on Mac/Linux, leaving off `__attribute__((visibility("default")))` causes a compile error. Turns out Chromium already has a tool for working around this and constructing the correct export syntax, so use that.
=> fix: export DebugOptions parser in a cross-platform-compatible way

doc/api/fs.md, lib/fs.js, test/parallel/test-fs-watch-close-when-destroyed.js, test/parallel/test-fs-watch.js
Resolves https://github.com/electron/electron/issues/14844.
This PR backports https://github.com/nodejs/node/pull/20985 to `3-0-x`.
The original fix went out in `v10.5.0`, so we don't need to backport it anywhere else since we'll cut `4-0-x` with at least Node `v10.10.0`.
/cc @pfrazee
=> fix: do not crash when using a closed fs event watcher

common.gypi, tools/generate_config_gypi.py
Resolves https://github.com/electron/electron/issues/6556.
Adds new `built_with_electron` variable to `config.gypi` generated by `tools/generate_config_gypi.py`
/cc @nornagon
=> feat: add new built_with_electron variable to config.gypi

BUILD.gn
Remove define precluding usage of `NODE_OPTIONS` in Electron in concert with https://github.com/electron/electron/pull/15158.
/cc @nornagon @deepak1556
=> fix: remove NODE_WITHOUT_NODE_OPTIONS

src/node_api.h
matches the change in node.h in 88b494191c, both are necessary because Chromium builds with symbols hidden by default
Fixes electron/electron#15168
=> fix: export napi symbols

BUILD.gn, deps/zlib/BUILD.gn
Changing Chrome's zlib to export symbols caused issues in component builds (https://github.com/electron/electron/pull/15138) -- so I've taken a different approach:
- use node's zlib instead of chrome's
- let node's zlib export symbols
There are no conflicts because Chrome's zlib is already "namespaced" (i.e. `Cr_z_foo`). This also means we can actually generate a legitimate node-gyp import library (`electron.lib`) in debug builds by combining `node_lib.dll.lib` and `v8.dll.lib` using `lib.exe`.
This feels like the "right" solution, however, going the other direction (leaning into Chrome's zlib) would, I think, necessitate us switching zlib to be a formal component (and handling whatever non-trivial fallout that would have in the Chrome tree). 
Lastly, simply only exporting zlib symbols in …
=> fix: use zlib from electron_node

BUILD.gn, src/inspector/BUILD.gn
Closes #91.
This reduces the likelihood that inspector could be assuming a different memory layout of Node data structures due to varying build flags.
=> refactor: split out main config so inspector can share

src/node_perf.cc
Backports acc5a86efe241b52a2e0bf8c6b1ba886213cf9f0.
=> fix: backport a node commit that cleans up GC listeners (5-0-x)

lib/internal/bootstrap/node.js, src/node_binding.h
Updates existing patches that relied on legacy binding to use linked binding . No functionality change intended here.
=> refactor: update patches to use process._linkedBinding

lib/fs.js
To reproduce this behaviour on Electron `3.1.x`, I have a test project setup (on Windows, but I don't think that matters here):
```
$ git clone https://github.com/shiftkey/electron-quick-start -b repro-fswatcher-this-issue
$ npm install
$ npm start
```
Open the dev tools, click the `Click me!` button, see the app break into your code:
Browse to the source of `fs.js` and put a break point inside `FSWatcher`'s ` `this._handle.onchange` callback (line 1382):
Resume the app and it should hit the `fs.js` breakpoint. Check the local scope:
Note that `this` inside the callback is the `FSEvent` associated with the `onchange` event, not the current `FSWatcher`. Further down the code uses `self.*` to emit events, and I think this was just a code path that rarely gets exercised.
I haven't triggered …
=> fix: use `self` instead of `this` inside FSWatcher onchange callback

deps/uv/src/unix/fsevents.c, deps/uv/test/test-fs-event.c, deps/uv/test/test-list.h
Backports https://github.com/libuv/libuv/pull/2313
=> fix: [deps/uv] fsevents: fix file event reporting (backport: v12.x)

lib/internal/main/run_main_module.js, lib/internal/modules/cjs/loader.js
This floats two patches onto the node 12 branch that I don't think we can upstream.
The default behavior of node is to `path.resolve(firstArg)` to figure out what JS file to load.  Issue here is that we use that for `browser/init.js` which now doesn't exist on disk.  This adds an exception that won't affect user code to allow node to boot-up internal modules (in this case anything in the `electron/js2c` scope.
Similar to the above, the loader uses `process.argv[1]` to figure out when to break for `--inspect-brk` this updates the logic to use an Electron provided `process._firstFileName`
=> chore: allow the node entrypoint to be a builtin module

lib/child_process.js
With crashpad on Windows, the child processes have to communicate with the crash handler process via named pipe, and the name of pipe is passed via environment variables.
This patch ensures the `ELECTRON_CRASHPAD_PIPE_NAME` env is always inherited in child processes, so crashReporter can work correctly in node scripts.
Refs https://github.com/electron/electron/pull/18483.
=> Inherit ELECTRON_CRASHPAD_PIPE_NAME in child process

BUILD.gn, tools/generate_config_gypi.py
Ref https://github.com/electron/electron/issues/18670
=> fix: enable ltcg on windows

src/inspector/BUILD.gn
Chromium changed the location of js_protocol.pdl:
https://chromium-review.googlesource.com/c/chromium/src/+/1665929
This PR updates to the new location.
=> chore: update location of js_protocol.pdl

BUILD.gn
hopefully this'll fix the error we've been seeing:
```
../../v8/include/v8config.h:357:2: error: Inconsistent build configuration: To build the V8 shared library set BUILDING_V8_SHARED, to include its headers for linking against the V8 shared library set USING_V8_SHARED.
```
=> fix: don't define BUILDING_V8_SHARED in component builds
